
package com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TransactionSearchOperationsSoap", targetNamespace = "PayFlexVPosUIServerWebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransactionSearchOperationsSoap {


    /**
     * 
     * @param request
     * @return
     *     returns com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.TransactionSearchResponse
     */
    @WebMethod(operationName = "SearchTransaction", action = "PayFlexVPosUIServerWebService/SearchTransaction")
    @WebResult(name = "SearchTransactionResult", targetNamespace = "PayFlexVPosUIServerWebService")
    @RequestWrapper(localName = "SearchTransaction", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SearchTransaction")
    @ResponseWrapper(localName = "SearchTransactionResponse", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SearchTransactionResponse")
    public TransactionSearchResponse searchTransaction(
        @WebParam(name = "request", targetNamespace = "PayFlexVPosUIServerWebService")
        TransactionSearchRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SearchResponse2
     */
    @WebMethod(operationName = "Search", action = "PayFlexVPosUIServerWebService/Search")
    @WebResult(name = "SearchResult", targetNamespace = "PayFlexVPosUIServerWebService")
    @RequestWrapper(localName = "Search", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SearchResponse")
    public SearchResponse2 search(
        @WebParam(name = "request", targetNamespace = "PayFlexVPosUIServerWebService")
        SearchRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SettlementResponse2
     */
    @WebMethod(operationName = "Settlement", action = "PayFlexVPosUIServerWebService/Settlement")
    @WebResult(name = "SettlementResult", targetNamespace = "PayFlexVPosUIServerWebService")
    @RequestWrapper(localName = "Settlement", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.Settlement")
    @ResponseWrapper(localName = "SettlementResponse", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SettlementResponse")
    public SettlementResponse2 settlement(
        @WebParam(name = "request", targetNamespace = "PayFlexVPosUIServerWebService")
        SettlementRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SettlementDetailResponse2
     */
    @WebMethod(operationName = "SettlementDetail", action = "PayFlexVPosUIServerWebService/SettlementDetail")
    @WebResult(name = "SettlementDetailResult", targetNamespace = "PayFlexVPosUIServerWebService")
    @RequestWrapper(localName = "SettlementDetail", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SettlementDetail")
    @ResponseWrapper(localName = "SettlementDetailResponse", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SettlementDetailResponse")
    public SettlementDetailResponse2 settlementDetail(
        @WebParam(name = "request", targetNamespace = "PayFlexVPosUIServerWebService")
        SettlementDetailRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SucceededOpenBatchTransactionsResponse2
     */
    @WebMethod(operationName = "SucceededOpenBatchTransactions", action = "PayFlexVPosUIServerWebService/SucceededOpenBatchTransactions")
    @WebResult(name = "SucceededOpenBatchTransactionsResult", targetNamespace = "PayFlexVPosUIServerWebService")
    @RequestWrapper(localName = "SucceededOpenBatchTransactions", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SucceededOpenBatchTransactions")
    @ResponseWrapper(localName = "SucceededOpenBatchTransactionsResponse", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SucceededOpenBatchTransactionsResponse")
    public SucceededOpenBatchTransactionsResponse2 succeededOpenBatchTransactions(
        @WebParam(name = "request", targetNamespace = "PayFlexVPosUIServerWebService")
        SucceededOpenBatchTransactionsRequest request);

    /**
     * 
     * @param batchTransactionSumDetailRequest
     * @return
     *     returns com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.BatchTransactionSumDetailResponse
     */
    @WebMethod(operationName = "SearchBatchTransactionSum", action = "PayFlexVPosUIServerWebService/SearchBatchTransactionSum")
    @WebResult(name = "SearchBatchTransactionSumResult", targetNamespace = "PayFlexVPosUIServerWebService")
    @RequestWrapper(localName = "SearchBatchTransactionSum", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SearchBatchTransactionSum")
    @ResponseWrapper(localName = "SearchBatchTransactionSumResponse", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.SearchBatchTransactionSumResponse")
    public BatchTransactionSumDetailResponse searchBatchTransactionSum(
        @WebParam(name = "batchTransactionSumDetailRequest", targetNamespace = "PayFlexVPosUIServerWebService")
        BatchTransactionSumDetailRequest batchTransactionSumDetailRequest);

    /**
     * 
     * @param editMerchantBatchTransactionSumRequest
     * @return
     *     returns com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.EditMerchantBatchTransactionSumResponse2
     */
    @WebMethod(operationName = "EditMerchantBatchTransactionSum", action = "PayFlexVPosUIServerWebService/EditMerchantBatchTransactionSum")
    @WebResult(name = "EditMerchantBatchTransactionSumResult", targetNamespace = "PayFlexVPosUIServerWebService")
    @RequestWrapper(localName = "EditMerchantBatchTransactionSum", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.EditMerchantBatchTransactionSum")
    @ResponseWrapper(localName = "EditMerchantBatchTransactionSumResponse", targetNamespace = "PayFlexVPosUIServerWebService", className = "com.gateway.payment_be.service.paymentproviderclient.vakifbank.dto.inquiry.EditMerchantBatchTransactionSumResponse")
    public EditMerchantBatchTransactionSumResponse2 editMerchantBatchTransactionSum(
        @WebParam(name = "editMerchantBatchTransactionSumRequest", targetNamespace = "PayFlexVPosUIServerWebService")
        EditMerchantBatchTransactionSumRequest editMerchantBatchTransactionSumRequest);

}
